name: icupa_vendor
description: "Icupa Vendor application"
publish_to: 'none'

version: 1.0.6+20

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cloud_firestore: ^5.0.1
  firebase_core: ^3.1.0
  firebase_storage: ^12.1.1
  geolocator: ^11.0.0
  location_geocoder: ^1.0.5
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  animation_wrappers: ^3.0.0
  pinput: ^5.0.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  modal_progress_hud_nsn: ^0.5.1
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  image_cropper: ^7.1.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  collection: ^1.18.0
  http: ^1.2.1
  google_maps_flutter: ^2.8.0
  map_autocomplete_field: ^0.0.2
  syncfusion_flutter_charts: ^26.1.41+1
  visibility_detector: ^0.4.0+2
  path: ^1.8.3
  fluttertoast: ^8.2.6
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.1+2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  generate: true

  assets:
    - assets/
    - assets/menu/
    - assets/account/
