// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX2rOX0b4o2UbfVR9o_rSWtxVjbN0xfKw',
    appId: '1:711859015599:android:2de1f1518c3c82c40fa95a',
    messagingSenderId: '711859015599',
    projectId: 'panacea-b4045',
    storageBucket: 'panacea-b4045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiol2KOzgL79Lcly1VAuwhh0garys1sBc',
    appId: '1:711859015599:ios:d15cde43db8538870fa95a',
    messagingSenderId: '711859015599',
    projectId: 'panacea-b4045',
    storageBucket: 'panacea-b4045.appspot.com',
    iosBundleId: 'com.panacea.pharmacy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjvjP4Z3JiTvnNe0ka__v4oG5wGAyUJX4',
    appId: '1:711859015599:web:f20cee0c77c0fbcf0fa95a',
    messagingSenderId: '711859015599',
    projectId: 'panacea-b4045',
    authDomain: 'panacea-b4045.firebaseapp.com',
    storageBucket: 'panacea-b4045.appspot.com',
    measurementId: 'G-WFSSB77F0W',
  );

}